server:
  port: 8088

spring:
  cloud:
    openfeign:
      oauth2:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          photostorybook-webclient:
            provider: photostorybook-auth-service
            client-id: photostorybook-webclient
            client-name: photostorybook-webclient
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8088/login/oauth2/code/{registrationId}"
            scope: openid,readPhotostory,writePhotostory,deletePhotostory
        provider:
          photostorybook-auth-service:
            issuer-uri: http://localhost:9000
