
debug: true

server:
  port: 8080

feign:
  oauth2:
    enabled: true
  client:
    refresh-enabled: true
    clientRegistrationId: photostorybook-auth-service

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: photostorybook-auth-service
      client:
        config:
          PhotostoryRestService:
            url: http://localhost:8081
            loggerLevel: full
  security:
    oauth2:
      client:
        registration:
          photostorybook-webclient:
            provider: photostorybook-auth-service
            client-id: photostorybook-webclient
            client-name: photostorybook-webclient
            client-secret: d0sEgh3IuxXsg1lh9qhRhsS1ngFfDtDi
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid,photostory.read,photostory.write,photostory.delete
        provider:
          photostorybook-auth-service:
            issuer-uri: http://localhost:9000/realms/PhotostoryBookRealm
            authorization-uri: http://localhost:9000/realms/PhotostoryBookRealm/protocol/openid-connect/auth
            token-uri: http://localhost:9000/realms/PhotostoryBookRealm/protocol/openid-connect/token
            user-info-uri: http://localhost:9000/realms/PhotostoryBookRealm/protocol/openid-connect/userinfo


