version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: 'keycloak'
    ports:
      - "9000:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./init/keycloak_partial_realm-export.json:/opt/keycloak/data/import/realm.json