openapi: 3.0.3
info:
  title: PhotostoryBook service API.
  description: REST API for PhotostoryBook App
  version: 0.0.1-SNAPSHOT
servers:
  - url: https://127.0.0.1:8080/
  - url: http://127.0.0.1:8080/
tags:
  - name: photostories
    description: This section contains photostory endpoints
  - name: photos
    description: This section contains endpoints related to photo
  - name: user
    description: This section contains user endpoints

paths:
  /photostories:
    get:
      operationId: getPhotostories
      tags:
        - photostories
      summary: Returns a list of all photostories

      description: |
        Returns a list of all photostories of the current authorized user.
      responses:
        200:
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhotostoryListResponse'
    post:
      operationId: addPhotostory
      tags:
        - photostories
      summary: Creates a new photostory
      description: |
        Creates a new photostory for the current authorized user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                storyTitle:
                  type: string
                  example: An awesome title for a new photostory.
      responses:
        201:
          description: Successfully created a new photostory.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhotostoryResponse'

  /photostories/{storyId}/photos:
    post:
      tags:
        - photos
      summary: Add a new photo to photostory identified by storyId
      operationId: uploadPhoto
      parameters:
        - in: path
          name: storyId
          description: photostory id
          required: true
          schema:
            type: string
            format: uuid
            pattern: '^[0-9a-fA-F\-]{36}$'
            example: "123e4567-e89b-12d3-a456-426614174000"
      requestBody:
        description: Photo image file in PNG format
        required: true
        content:
          image/png:
            schema:
              type: string
              format: binary
          image/jpeg:
            schema:
              type: string
              format: binary
      responses:
        201:
          description: Successfully upload a photo.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhotoIdResponse'

components:
  schemas:
    PhotostoryResponse:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          pattern: '^[0-9a-fA-F\-]{36}$'
          example: "123e4567-e89b-12d3-a456-426614174000"
        storyTitle:
          type: string
          example: An awesome title for a new photostory.
        titlePhotoURI:
          type: string
      required:
        - uuid
        - storyTitle
    PhotostoryListResponse:
      type: object
      properties:
        photostories:
          type: array
          items:
            $ref: '#/components/schemas/PhotostoryResponse'
    PhotoIdResponse:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          pattern: '^[0-9a-fA-F\-]{36}$'
      required:
        - uuid


